### 회원가입 ( 고객 )
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "email": "februstar11@gmail",
  "name": "jisue",
  "password": "pw",
  "birth": "2024-09-04",
  "phone": "01000000000"
}

### 이메일 인증 ( 고객 )
GET http://localhost:8081/signup/customer/verify?email=februstar11@gmail&code=

### 로그인 ( 고객 )
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "februstar11@gmail",
  "password": "pw"
}

### 회원 정보 조회 ( 고객 )
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: ***

### 잔액 변경 ( 고객 )
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: ***

{
  "from": "server",
  "message": "돈 충전",
  "money": 50000
}

##############

### 회원가입 ( 셀러 )


###